.TH 6pm "1" "Avril 2016" "6pm 0.9" "Commandes utilisateur"

.SH NOM
6PM \- Synthétiseur par modulation de phase (PM) fait à partir de 6 oscillateurs.

.SH SYNOPSIS
.B 6pm

.SH DESCRIPTION
6pm 0.9 [30 Avr 2016] [http://sourceforge.net/projects/mv\-6pm/].
.PP
6pm est fourni SANS AUCUNE GARANTIE.
.PP
C'est un logiciel libre, et vous êtes invité à le redistributer sous certaines conditions. Voir le fichier LICENSE pour les détails.

.SH OPTIONS
.TP 
.if  !'po4a'hide' .BR \-h ", " \-\-help
Donne quelques informations.
.TP 
.if  !'po4a'hide' .BR \-\-nogui
Fonctionnement sans interface graphique. Ceci devrait réduire l'empreinte processeur, spécialement sur des machines faibles.

.SH AUTEUR
Michel Vergnaud \- Copyright 2015\-2016.
.PP
Cette page de manuel a été écrite par Olivier Humbert entre Janvier et Avril 2016 pour le projet LibraZiK et peut être utilisée par tout un chacun.
