.TH 6pm "1" "January 2016" "6pm 0.80.1" "User Commands"

.SH NAME
6PM \- Phase modulation (PM) synthesizer made of six oscillators.

.SH SYNOPSIS
.B 6pm

.SH DESCRIPTION
6pm 0.80.1 [Jan 19 2016] [http://sourceforge.net/projects/mv\-6pm/].
.PP
6pm comes with ABSOLUTELY NO WARRANTY.
.PP
This is free software, and you are welcome to redistribute it under certain conditions. See the file LICENSE for details.

.SH AUTHOR
Michel Vergnaud \- Copyright 2015\-2016.
.PP
This man page has been written by Olivier Humbert on Tuesday the 19th of January 2016 for the LibraZiK project and can be used by anyone.
